version: '3.7'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'administrador'
      MYSQL_DATABASE: 'cawastore'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'administrador'
    ports:
      - 3306:3306
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    restart: 'no'

  redis:
    container_name: redis
    image: 'redis:latest'
    command: redis-server --requirepass administrador
    ports:
      - '6379:6379'

  
  haproxy-web:
     container_name: haproxy-web
     image: 'haproxy:2.1'
     ports:
       - '81:80'
       - '443:443'
       - '8404:8404'
     volumes:
       - ./volumes/haproxy-web:/usr/local/etc/haproxy:ro
     depends_on:
       - cawastore-web-1
       - cawastore-web-2

  cawastore-web-1:
     container_name: cawastore-web-1
     # build:
       # context: .
       # dockerfile: Dockerfile
     image: 'gonpg/cawastore-web:2'
     depends_on:
       - mysql
       - redis

  cawastore-web-2:
     container_name: cawastore-web-2
     image: 'gonpg/cawastore-web:2'
     depends_on:
       - mysql
       - redis